# mode(debug,test,release)
RunMode = "release"

# Whether to print configuration parameters at startup
PrintConfig = true

# Information about themselves
[Common]
UniqueId = "za-sentinel"
AppName = "za-sentinel"
ControHost = "https://net.ztalab.xyz"

# Certificate Information
[Certificate]
# Cert base64
CertPem = ""
# Cert path
CertPemPath = "./cert/cert.pem"
# Key cert base64
KeyPem = ""
# Key path
KeyPemPath = "./cert/key.pem"
# ca cert base64
CaPem = ""
# ca cert path
CaPemPath = "./cert/ca.pem"

[Influxdb]
Enabled = false
Address = "127.0.0.1"
Port = 18086
Username = "username"
Password = "password"
Database = "msp"
Precision = "ms"
MaxIdleConns = 30
MaxIdleConnsPerHost = 30
FlushTime = 20
FlushSize = 10

[Log]
# level(1:fatal,2:error,3:warn,4:info,5:debug,6:trace)
Level = 6
# text、json
Format = "text"
# stdout、stderr、file
Output = "stdout"
OutputFile = "data/logger.log"
EnableHook = false
HookLevels = ["info", "warn", "error"]
# gorm、redis
Hook = "redis"
HookMaxThread = 1
HookMaxBuffer = 512

[LogRedisHook]
Addr = "127.0.0.1:6379"
Key = "msp"
